site_name: pytest-betterdiff
site_description: A plugin providing an alternative, colourful, ExUnit inspired diff output for failing assertions.
site_author: Darren Burns

theme: readthedocs

repo_url: https://github.com/darrenburns/pytest-betterdiff

pages:
- Home: index.md
